### PR TITLE
Multiplayer mvp

### PR DESCRIPTION
**Pull request by peternga**
Basic multiplayer functionality. Still need to improve packaging and building.

* Adds Express server
* Adds Gecko server for real-time behavior
* Coordinates scene transitions amongst clients
* Shares connected players in lobby

### CODE REVIEW

**Comment by peternga** [comment]
I'm not sure if this will work when deployed in Heroku...something about dynamic ports. The server should pick up the port but I'm not sure about the client. I have the client pull the port from the URL but that might not work. An alternative is to add a screen to allow the client to specify the port, but I feel like we should be able to know which port is exposed on the server.

**Comment by nathanleiby** [comment]
Very cool! I'm trying to test it locally or on the web. Any tips on commands to run / things to test? (I'll poke around too)

**Comment by nathanleiby** [comment]
Would the client connect to port 80 (or 443 if exposed by HTTPS), if that's the port the webapp is ultimately shared at? I don't know if it matters what port that app is running on internally.

https://stackoverflow.com/questions/28706180/setting-the-port-for-node-js-server-on-heroku

**Comment by nathanleiby** [comment]
Here's what I did to get things running locally

Get dependencies installed (mine got in a bad state when i just ran `npm install:`, so i nuked and started fresh):

```
rm -rf node_modules
npm install
```

Run the server:

```
npm build
npm run startProd
```

Hack the client code by changing this line
https://github.com/clevergamedev/letterjam/blob/master/src/client/scripts/scenes/preloadScene.ts#L7
to be hard-coded to `3000` (otherwise, it used `8080`)

Run the client locally (via the dev-server):

```
npm start
```

---

Go to `localhost:8080` and it's good! Opened 3 tabs and verified that state gets updated in other tabs when I click in one!

**Comment by nathanleiby** [comment]
Interesting bug seen... in the tab where I clicked around things look good:

Letter_Jam

but in another tab (as another client/player), I see:

Letter_Jam

**Comment by peternga** [comment]
I tried to set the port to 80 as suggested in other posts but it didn't work for me. I was going to spend some time later today working out those kinks. I don't think 443 would work since it's an `http` protocol rather than an `https`

**Comment by peternga** [comment]
Interesting bug. How many clients did you have when that happened?

The way I've been running locally is:
```
npm run build
npm run startProd
Navigate to localhost:3000
```
Is it possible there's a bug because two different servers are trying to serve up the code? I'm surprised there isn't an error trying to listen to the same port.

I think there's some things we can do to improve the dev experience like having a startDev via nodemon, adding transpiling to server code, etc. I plan on looking into that once I figure out the Heroku port issue

**Comment by nathanleiby** [comment]
1. I think it just doesn't work in Firefox yet, which was causing some confusion for me.
2. I got the code working the way you described in Chrome. Didn't need to run a dev-server and a prod server. I was confused.
3. Added steps to repro the bug here: https://github.com/CleverGameDev/LetterJam/issues/10

**Pull request merged**
