### PR TITLE
Expose port on endpoint for client

### PR DESCRIPTION
**Pull request by peternga**

### CODE REVIEW

**Comment by nathanleiby** [comment]
Was this causing things to work on Heroku for you? When I tested I just saw a white screen, hence my change here: https://github.com/CleverGameDev/LetterJam/pull/11 but if you had seen it work please LMK and revert that!

**Comment by peternga** [comment]
No, it was still a white screen. I've been fiddling around with it but still no dice. I've seen documentation around getting socket.io up on Heroku so I feel like other websocket technologies should also work but nothing yet.

**Comment by nathanleiby** [comment]
Seems like this recent change in geckos.io v1.7 is related https://github.com/geckosio/geckos.io/commit/60841fca0bfc40879f98681d47cd9181c784fb61

Here's the port range for Heroku: https://help.heroku.com/BXGG53I6/what-is-the-range-of-the-dynamic-port-environment-variable

**Comment by nathanleiby** [comment]
Also potentially a useful guide: https://devcenter.heroku.com/articles/node-websockets

**Pull request merged**
